package com.commercesuite.common.api;

public enum ErrorCode {
    VALIDATION_FAILED,
    UNAUTHENTICATED,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    ACCOUNT_LOCKED,
    ACCOUNT_NOT_ACTIONABLE,
    INVALID_CREDENTIALS,
    TOKEN_INVALID,
    TOKEN_EXPIRED,
    REFRESH_REUSE_DETECTED,
    EMAIL_TAKEN,
    PHONE_TAKEN,
    WEAK_PASSWORD,
    RATE_LIMITED,
    INTERNAL_ERROR
}
